In [1]:
import gspread
import pprint
from oauth2client.service_account import ServiceAccountCredentials
from tabulate import tabulate
import pandas as pd

In [2]:
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name('bank_secret.json', scope)
client = gspread.authorize(creds)

In [5]:
def get_lowest_bank(file_name, bank_name):
    sheet = client.open(file_name.lower()).sheet1
    data = pd.DataFrame(sheet.get_all_records())

    interest_rate = data.groupby('Bank_Name')
    bank_programs = interest_rate.get_group(bank_name)
    sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
    top_lowest = sorted.iloc[0:5]
    return top_lowest

In [4]:
get_lowest_bank('casa_bank', 'CommBank (CM)')

        Bank_Name        Package fixedInterval interestRate   maxAmount  \
8   CommBank (CM)  FixedHomeLoan             5         3.09  10,000,000
2   CommBank (CM)  FixedHomeLoan             2         3.79  10,000,000
5   CommBank (CM)  FixedHomeLoan             3         3.79  10,000,000
13  CommBank (CM)  FixedHomeLoan             2         3.89           ~
0   CommBank (CM)  FixedHomeLoan             1         3.89  10,000,000

   maxInsuredLVR maxLVR maxTerm minAmount minTerm programId purpose  \
8            95%    80%      30    10,000       1   CMFHOU9      OU
2            95%    80%      30    10,000       1   CMFHOU3      OU
5            95%    80%      30    10,000       1   CMFHOU6      OU
13           90%    80%      30    10,000       1   CMFHIV4      IV
0            95%    80%      30    10,000       1   CMFHOU1      OU

   repaymentType
8            P&I
2            P&I
5            P&I
13           P&I
0            P&I

,Bank_Name,Package,fixedInterval,interestRate,maxAmount,maxInsuredLVR,maxLVR,maxTerm,minAmount,minTerm,programId,purpose,repaymentType
8,CommBank (CM),FixedHomeLoan,5,3.09,"10,000,000",95%,80%,30,"10,000",1,CMFHOU9,OU,P&I
2,CommBank (CM),FixedHomeLoan,2,3.79,"10,000,000",95%,80%,30,"10,000",1,CMFHOU3,OU,P&I
5,CommBank (CM),FixedHomeLoan,3,3.79,"10,000,000",95%,80%,30,"10,000",1,CMFHOU6,OU,P&I
13,CommBank (CM),FixedHomeLoan,2,3.89,~,90%,80%,30,"10,000",1,CMFHIV4,IV,P&I
0,CommBank (CM),FixedHomeLoan,1,3.89,"10,000,000",95%,80%,30,"10,000",1,CMFHOU1,OU,P&I

In [6]:
get_lowest_bank('casa_bank', 'CommBank (CM)')

,Bank_Name,Package,fixedInterval,interestRate,maxAmount,maxInsuredLVR,maxLVR,maxTerm,minAmount,minTerm,programId,purpose,repaymentType
8,CommBank (CM),FixedHomeLoan,5,3.09,"10,000,000",95%,80%,30,"10,000",1,CMFHOU9,OU,P&I
2,CommBank (CM),FixedHomeLoan,2,3.79,"10,000,000",95%,80%,30,"10,000",1,CMFHOU3,OU,P&I
5,CommBank (CM),FixedHomeLoan,3,3.79,"10,000,000",95%,80%,30,"10,000",1,CMFHOU6,OU,P&I
13,CommBank (CM),FixedHomeLoan,2,3.89,~,90%,80%,30,"10,000",1,CMFHIV4,IV,P&I
0,CommBank (CM),FixedHomeLoan,1,3.89,"10,000,000",95%,80%,30,"10,000",1,CMFHOU1,OU,P&I

In [7]:
get_lowest_bank('casa_bank', 'ANZ (AN)')

,Bank_Name,Package,fixedInterval,interestRate,maxAmount,maxInsuredLVR,maxLVR,maxTerm,minAmount,minTerm,programId,purpose,repaymentType
53,ANZ (AN),FixedRate,2,3.9,"10,000,000",95%,80%,30,"20,000",2,ANFROU3,OU,P&I
67,ANZ (AN),FixedRate,2,4.1,"10,000,000",95%,80%,30,"20,000",2,ANFRIV3,IV,P&I
56,ANZ (AN),FixedRate,3,4.14,"10,000,000",95%,80%,30,"20,000",3,ANFROU6,OU,IO
52,ANZ (AN),FixedRate,1,4.24,"10,000,000",95%,80%,30,"20,000",1,ANFROU2,OU,IO
68,ANZ (AN),FixedRate,2,4.33,"10,000,000",95%,80%,30,"20,000",1,ANFRIV4,IV,IO

In [10]:
def get_lowest_bank(file_name, bank_name=None, mortgage=None):
    sheet = client.open(file_name.lower()).sheet1
    data = pd.DataFrame(sheet.get_all_records())
    if(bank_name != None):
        interest_rate = data.groupby('Bank_Name')
        bank_programs = interest_rate.get_group(bank_name)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.iloc[0:5]
    elif(mortgage != None):
        mortgage_type = data.groupby('repaymentType')
        bank_programs = mortgage_type.get_group(mortgage)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.iloc[0:13]
    else:
        sorted = data.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.iloc[0:5]
    return top_lowest

In [11]:
get_lowest_bank('casa_bank', 'CommBank (CM)', 'IO')

,Bank_Name,Package,fixedInterval,interestRate,maxAmount,maxInsuredLVR,maxLVR,maxTerm,minAmount,minTerm,programId,purpose,repaymentType
8,CommBank (CM),FixedHomeLoan,5,3.09,"10,000,000",95%,80%,30,"10,000",1,CMFHOU9,OU,P&I
2,CommBank (CM),FixedHomeLoan,2,3.79,"10,000,000",95%,80%,30,"10,000",1,CMFHOU3,OU,P&I
5,CommBank (CM),FixedHomeLoan,3,3.79,"10,000,000",95%,80%,30,"10,000",1,CMFHOU6,OU,P&I
13,CommBank (CM),FixedHomeLoan,2,3.89,~,90%,80%,30,"10,000",1,CMFHIV4,IV,P&I
0,CommBank (CM),FixedHomeLoan,1,3.89,"10,000,000",95%,80%,30,"10,000",1,CMFHOU1,OU,P&I

In [12]:
def get_lowest_bank(file_name, bank_name=None, mortgage=None):
    sheet = client.open(file_name.lower()).sheet1
    data = pd.DataFrame(sheet.get_all_records())
    if(bank_name != None):
        interest_rate = data.groupby('Bank_Name')
        bank_programs = interest_rate.get_group(bank_name)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.iloc[0:5]
    elif(mortgage != None):
        mortgage_type = data.groupby('repaymentType')
        bank_programs = mortgage_type.get_group(mortgage)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.iloc[0:13]
    else:
        sorted = data.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.iloc[0:5]
    return top_lowest

In [13]:
get_lowest_bank('casa_bank', 'CommBank (CM)', 'IO')

,Bank_Name,Package,fixedInterval,interestRate,maxAmount,maxInsuredLVR,maxLVR,maxTerm,minAmount,minTerm,programId,purpose,repaymentType
8,CommBank (CM),FixedHomeLoan,5,3.09,"10,000,000",95%,80%,30,"10,000",1,CMFHOU9,OU,P&I
2,CommBank (CM),FixedHomeLoan,2,3.79,"10,000,000",95%,80%,30,"10,000",1,CMFHOU3,OU,P&I
5,CommBank (CM),FixedHomeLoan,3,3.79,"10,000,000",95%,80%,30,"10,000",1,CMFHOU6,OU,P&I
13,CommBank (CM),FixedHomeLoan,2,3.89,~,90%,80%,30,"10,000",1,CMFHIV4,IV,P&I
0,CommBank (CM),FixedHomeLoan,1,3.89,"10,000,000",95%,80%,30,"10,000",1,CMFHOU1,OU,P&I

In [16]:
def get_lowest_bank(file_name, bank_name=None, mortgage=None):
    sheet = client.open(file_name.lower()).sheet1
    data = pd.DataFrame(sheet.get_all_records())
    if(bank_name != None):
        if(mortgage != None):
            mortgage_type = data.groupby('repaymentType')
            bank_programs = mortgage_type.get_group(mortgage)
            sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
            top_lowest = sorted.iloc[0:50]
        else:
            interest_rate = data.groupby('Bank_Name')
            bank_programs = interest_rate.get_group(bank_name)
            sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
            top_lowest = sorted.iloc[0:5]
    elif(mortgage != None):
        mortgage_type = data.groupby('repaymentType')
        bank_programs = mortgage_type.get_group(mortgage)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.iloc[0:5]
    else:
        sorted = data.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.iloc[0:5]
    return top_lowest

In [17]:
get_lowest_bank('casa_bank', 'CommBank (CM)', 'IO')

,Bank_Name,Package,fixedInterval,interestRate,maxAmount,maxInsuredLVR,maxLVR,maxTerm,minAmount,minTerm,programId,purpose,repaymentType
56,ANZ (AN),FixedRate,3,4.14,"10,000,000",95%,80%,30,"20,000",3,ANFROU6,OU,IO
33,Westpac (W),FixedPremier,2,4.15,"249,999",95%,80%,30,"150,000",1,WFPIV4,IV,IO
12,CommBank (CM),FixedHomeLoan,2,4.19,~,90%,80%,30,"10,000",2,CMFHIV3,IV,IO
15,CommBank (CM),FixedHomeLoan,3,4.19,~,90%,80%,30,"10,000",3,CMFHIV6,IV,IO
52,ANZ (AN),FixedRate,1,4.24,"10,000,000",95%,80%,30,"20,000",1,ANFROU2,OU,IO
3,CommBank (CM),FixedHomeLoan,2,4.29,~,95%,80%,30,"10,000",2,CMFHOU4,OU,IO
35,Westpac (W),FixedPremier,3,4.29,"249,999",95%,80%,30,"150,000",1,WFPIV6,IV,IO
68,ANZ (AN),FixedRate,2,4.33,"10,000,000",95%,80%,30,"20,000",1,ANFRIV4,IV,IO
4,CommBank (CM),FixedHomeLoan,3,4.34,~,95%,80%,30,"10,000",3,CMFHOU5,OU,IO
70,ANZ (AN),FixedRate,3,4.34,"10,000,000",95%,80%,30,"20,000",1,ANFRIV6,IV,IO
60,ANZ (AN),FixedRate,5,4.34,"10,000,000",95%,80%,30,"20,000",5,ANFROU10,OU,IO
10,CommBank (CM),FixedHomeLoan,1,4.39,~,90%,80%,30,"10,000",1,CMFHIV1,IV,IO
30,Westpac (W),FixedPremier,1,4.39,"249,999",95%,80%,30,"150,000",1,WFPIV1,IV,IO
22,Westpac (W),FixedPremier,2,4.49,"10,000,000",95%,80%,30,"150,000",1,WFPOU3,OU,IO
1,CommBank (CM),FixedHomeLoan,1,4.54,~,95%,80%,30,"10,000",1,CMFHOU2,OU,IO
24,Westpac (W),FixedPremier,3,4.59,"10,000,000",95%,80%,30,"150,000",1,WFPOU5,OU,IO
21,Westpac (W),FixedPremier,1,4.59,"10,000,000",95%,80%,30,"150,000",1,WFPOU2,OU,IO
7,CommBank (CM),FixedHomeLoan,4,4.64,~,95%,80%,30,"10,000",4,CMFHOU8,OU,IO
54,ANZ (AN),FixedRate,2,4.64,"10,000,000",95%,80%,30,"20,000",2,ANFROU4,OU,IO
58,ANZ (AN),FixedRate,4,4.64,"10,000,000",95%,80%,30,"20,000",4,ANFROU8,OU,IO
66,ANZ (AN),FixedRate,1,4.69,"10,000,000",95%,80%,30,"20,000",1,ANFRIV2,IV,IO
17,CommBank (CM),FixedHomeLoan,4,4.89,~,90%,80%,30,"10,000",4,CMFHIV8,IV,IO
9,CommBank (CM),FixedHomeLoan,5,4.89,~,95%,80%,30,"10,000",5,CMFHOU10,OU,IO
38,Westpac (W),FixedPremier,5,4.95,"249,999",95%,80%,30,"150,000",1,WFPIV9,IV,IO
26,Westpac (W),FixedPremier,4,4.99,"10,000,000",95%,80%,30,"150,000",1,WFPOU7,OU,IO
18,CommBank (CM),FixedHomeLoan,5,4.99,~,90%,80%,30,"10,000",5,CMFHIV9,IV,IO
36,Westpac (W),FixedPremier,4,5.09,"249,999",95%,80%,30,"150,000",1,WFPIV7,IV,IO
29,Westpac (W),FixedPremier,5,5.09,"10,000,000",95%,80%,30,"150,000",1,WFPOU10,OU,IO
72,ANZ (AN),FixedRate,4,5.14,"10,000,000",95%,80%,30,"20,000",1,ANFRIV8,IV,IO
74,ANZ (AN),FixedRate,5,5.14,"10,000,000",95%,80%,30,"20,000",1,ANFRIV10,IV,IO
62,ANZ (AN),FixedRate,7,7.69,"10,000,000",95%,80%,30,"20,000",7,ANFROU12,OU,IO
64,ANZ (AN),FixedRate,10,7.69,"10,000,000",95%,80%,30,"20,000",10,ANFROU14,OU,IO
76,ANZ (AN),FixedRate,7,7.69,"10,000,000",95%,80%,30,"20,000",1,ANFRIV14,IV,IO
78,ANZ (AN),FixedRate,10,7.69,"10,000,000",95%,80%,30,"20,000",1,ANFRIV20,IV,IO

In [53]:
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name('bank_secret.json', scope)
client = gspread.authorize(creds)
def get_lowest_bank(file_name, bank_name=None, mortgage=None, yearFixed=None):
    sheet = client.open(file_name.lower()).sheet1
    data = pd.DataFrame(sheet.get_all_records())
    if(bank_name != None and mortgage != None and yearFixed != None):
        group = data.groupby('Bank_Name')
        bank_programs = group.get_group(bank_name)
        group = bank_programs.groupby('repaymentType')
        bank_programs = group.get_group(mortgage)
        group = bank_programs.groupby('fixedInterval')
        bank_programs = group.get_group(yearFixed)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.head(5)
    elif(bank_name != None and mortgage != None):
        group = data.groupby('Bank_Name')
        bank_programs = group.get_group(bank_name)
        group = bank_programs.groupby('repaymentType')
        bank_programs = group.get_group(mortgage)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.head(5)
    elif(bank_name != None and yearFixed != None):
        group = data.groupby('Bank_Name')
        bank_programs = group.get_group(bank_name)
        group = bank_programs.groupby('fixedInterval')
        bank_programs = group.get_group(yearFixed)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.head(5)
    elif(mortgage != None and yearFixed != None):
        group = data.groupby('repaymentType')
        bank_programs = group.get_group(mortgage)
        group = bank_programs.groupby('fixedInterval')
        bank_programs = group.get_group(yearFixed)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.head(5)
    elif(bank_name != None):
        group = data.groupby('Bank_Name')
        bank_programs = group.get_group(bank_name)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.head(5)
    elif(mortgage != None):
        group = data.groupby('repaymentType')
        bank_programs = group.get_group(mortgage)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.head(5)
    elif(yearFixed != None):
        group = data.groupby('fixedInterval')
        bank_programs = group.get_group(yearFixed)
        sorted = bank_programs.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.head(5)
    else:
        sorted = data.sort_values(by=['interestRate'], ascending=True)
        top_lowest = sorted.head(5)

    return top_lowest

In [54]:
get_lowest_bank('casa_bank', 'CommBank (CM)', 'IO', 2)

,Bank_Name,Package,fixedInterval,interestRate,maxAmount,maxInsuredLVR,maxLVR,maxTerm,minAmount,minTerm,programId,purpose,repaymentType
12,CommBank (CM),FixedHomeLoan,2,4.19,~,90%,80%,30,"10,000",2,CMFHIV3,IV,IO
3,CommBank (CM),FixedHomeLoan,2,4.29,~,95%,80%,30,"10,000",2,CMFHOU4,OU,IO